import type { NextPage } from "next";
import Head from "next/head";
import React, {useState } from "react";

const Home: NextPage = () => {
  const [menu, setMenu] = useState(false);
  const [toggle,setToggle] = useState(false)
  const clickmenuHandler = () => {
    setMenu(true);
  };

  const clickcloseHandler = () => {
    setMenu(false);
  };

  const togglerHandler = ()=>{
      setToggle(!toggle)

  }

 
 
  return (
   
    <div className={`${toggle && "dark-theme-variables"}`}>
  
    <div className="container">
      <Head>
        <title>Dashboard Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
        />
      </Head>
      <aside className={`${menu ? "menu-side" : "menu-none"}`}>
        <div className="top">
          <div className="logo">
            <img src="/Coffeebutton.png" alt="" />
            <h2>
              Dash <span className="danger">Board</span>
            </h2>
          </div>
          <div onClick={clickcloseHandler} className="close">
            <span className="material-symbols-outlined">close</span>{" "}
          </div>
        </div>
        <div className="sidebar">
          <a href="#">
            <span className="material-symbols-outlined">dashboard</span>
            <h3>Dashnoard</h3>
          </a>
          <a href="#" className="active">
            <span className="material-symbols-outlined">person</span>{" "}
            <h3>Customers</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">list_alt</span>{" "}
            <h3>Orders</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">trending_up</span>{" "}
            <h3>Analytics</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">mail</span>{" "}
            <h3>Messages</h3>
            <span className="messageCont">26</span>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">inventory</span>{" "}
            <h3>Products</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">report</span>{" "}
            <h3>Reports</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">settings</span>{" "}
            <h3>Settings</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">add</span>{" "}
            <h3>Add Product</h3>
          </a>
          <a href="#">
            <span className="material-symbols-outlined">logout</span>{" "}
            <h3>Logout</h3>
          </a>
        </div>
      </aside>
      {/* ------------------------------right----------------------------------------------- */}
      <main>
        <h1>Dashboard</h1>

        <div className="date">
          <input type="date" />
        </div>
        <div className="insights">
          <div className="sales">
            <span className="material-symbols-outlined">analytics</span>
            <div className="middle">
              <div className="left">
                <h3>Total sales</h3>
                <h1>$25,024</h1>
              </div>
              <div className="progress">
                <svg>
                  <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div className="number">
                  <p>81%</p>
                </div>
              </div>
            </div>
            <small className="text-muted">Last 24 Hours</small>
          </div>
          <div className="expenses">
            <span className="material-symbols-outlined">bar_chart</span>
            <div className="middle">
              <div className="left">
                <h3>Total Expenses</h3>
                <h1>$14,016</h1>
              </div>
              <div className="progress">
                <svg>
                  <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div className="number">
                  <p>62%</p>
                </div>
              </div>
            </div>
            <small className="text-muted">Last 24 Hours</small>
          </div>
          <div className="income">
            <span className="material-symbols-outlined">
              stacked_line_chart
            </span>
            <div className="middle">
              <div className="left">
                <h3>Total Income</h3>
                <h1>$24,564</h1>
              </div>
              <div className="progress">
                <svg>
                  <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div className="number">
                  <p>44%</p>
                </div>
              </div>
            </div>
            <small className="text-muted">Last 24 Hours</small>
          </div>
        </div>
        {/* -------------------------centertop----------------------------------- */}
        <div className="recent-orders">
          <h2>Recent Orders</h2>
          <table>
            <thead>
              <tr>
                <th>Product Name</th>
                <th>Product Number</th>
                <th>Payment</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Foldable Mini Drone</td>
                <td>85631</td>
                <td>Due</td>
                <td className="warning">Pending</td>
                <td className="primary">Details</td>
              </tr>
              <tr>
                <td>Foldable Mini Drone</td>
                <td>85631</td>
                <td>Due</td>
                <td className="warning">Pending</td>
                <td className="primary">Details</td>
              </tr>
              <tr>
                <td>Foldable Mini Drone</td>
                <td>85631</td>
                <td>Due</td>
                <td className="warning">Pending</td>
                <td className="primary">Details</td>
              </tr>
              <tr>
                <td>Foldable Mini Drone</td>
                <td>85631</td>
                <td>Due</td>
                <td className="warning">Pending</td>
                <td className="primary">Details</td>
              </tr>
              <tr>
                <td>Foldable Mini Drone</td>
                <td>85631</td>
                <td>Due</td>
                <td className="warning">Pending</td>
                <td className="primary">Details</td>
              </tr>
            </tbody>
          </table>
          <a href="#">Show All</a>
        </div>
      </main>
      {/* ------------------------------centerbottom-------------------------------------- */}
      <div className="right">
        <div className="top">
          <button onClick={clickmenuHandler} style={{ border: "none" }}>
            <span className="material-symbols-outlined">menu</span>
          </button>
          <div onClick={togglerHandler} id="theme-toggler" className="theme-toggler">
            <span   className={`material-symbols-outlined ${!toggle && "active"}`}>light_mode</span>
            <span  className={`material-symbols-outlined ${toggle && "active"}`}>dark_mode</span>
          </div>
          <div className="profile">
            <div className="info">
              <p>
                Hey, <b>Mohammad</b>
              </p>
              <small className="text-muted">Admin</small>
            </div>
            <div className="profile-photo">
              <img src="./Coffeebutton.png" alt="" />
            </div>
          </div>
        </div>
        {/* --------------------------------top-right------------------------------------------------- */}
        <div className="recent-updates">
          <h2>Recent Updates</h2>
          <div className="updates">
            <div className="update">
              <div className="profile-photo">
                <img src="./Coffeebutton.png" alt="" />
              </div>
              <div className="message">
                <p>
                  <b>Mahsa</b>reseived his order of night lion tech GPS done.
                </p>
                <small className="text-muted">2 Minutes Ago</small>
              </div>
            </div>
            <div className="update">
              <div className="profile-photo">
                <img src="./Coffeebutton.png" alt="" />
              </div>
              <div className="message">
                <p>
                  <b>Mahsa</b>reseived his order of night lion tech GPS done.
                </p>
                <small className="text-muted">2 Minutes Ago</small>
              </div>
            </div>
            <div className="update">
              <div className="profile-photo">
                <img src="./Coffeebutton.png" alt="" />
              </div>
              <div className="message">
                <p>
                  <b>Mahsa</b>reseived his order of night lion tech GPS done.
                </p>
                <small className="text-muted">2 Minutes Ago</small>
              </div>
            </div>
          </div>
        </div>
        {/* ------------------------------------------------------------------------------------ */}
        <div className="sales-analytics">
          <h2>Sales Analytics</h2>
          <div className="item online">
            <div className="icon">
              <span className="material-symbols-outlined">shopping_cart</span>
            </div>
            <div className="right">
              <div className="info">
                <h3>ONLINE ORDERS</h3>
                <small className="text-muted">Last 24 Hours</small>
              </div>
              <h5 className="success">+39%</h5>
              <h3>3849</h3>
            </div>
          </div>
          <div className="item offline">
            <div className="icon">
              <span className="material-symbols-outlined">local_mall</span>
            </div>
            <div className="right">
              <div className="info">
                <h3>OFFLINE ORDERS</h3>
                <small className="text-muted">Last 24 Hours</small>
              </div>
              <h5 className="danger">-17%</h5>
              <h3>1100</h3>
            </div>
          </div>
          <div className="item customrs">
            <div className="icon">
              <span className="material-symbols-outlined">person</span>
            </div>
            <div className="right">
              <div className="info">
                <h3>NEW CUSTOMRS</h3>
                <small className="text-muted">Last 24 Hours</small>
              </div>
              <h5 className="success">+25%</h5>
              <h3>849</h3>
            </div>
          </div>
          <div className="item add-product">
            <div>
              <span className="material-symbols-outlined">add</span>
              <h3>Add Product</h3>
            </div>
          </div>
        </div>
      </div>
    </div>

    </div>
  );
};

export default Home;
